services:
  karaoke-eternal:
    image: radrootllc/karaoke-eternal
    container_name: karaoke-eternal
    restart: unless-stopped
    hostname: karaoke-eternal
    networks:
    - traefik_network
    labels:
    - homepage.description=Personal Media Server
    - homepage.group=Media
    - homepage.href=https://karaoke-eternal.${DOMAINNAME}/
    - homepage.icon=karaoke-eternal
    - homepage.name=Karaoke-eternal
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=karaoke-eternal
    - traefik.enable=true
    - traefik.http.routers.karaoke-eternal.rule=Host(`karaoke-eternal.${DOMAINNAME}`)
    - traefik.http.services.karaoke-eternal.loadbalancer.server.port=8080
    volumes:
    - ${APPDATA_DIR}:/config
    - ${MEDIA_DIR}/music:/mnt/karaoke
