services:
  picoshare:
    image: mtlynch/picoshare
    environment:
    - PORT=4001
    - PS_SHARED_SECRET=${ADMIN_PASSWORD}
    command: -db /data/store.db
    container_name: picoshare
    hostname: picoshare
    networks:
    - traefik_network
    labels:
    - homepage.description=Minimalist File Sharing
    - homepage.group=File Transfer
    - homepage.href=https://picoshare.${DOMAINNAME}/
    - homepage.icon=mdi-share-outline
    - homepage.name=Picoshare
    - sablier-station.duration=15m
    - sablier-station.primary=true
    - sablier.enable=true
    - sablier.group=picoshare
    - traefik.enable=true
    - traefik.http.routers.picoshare.rule=Host(`picoshare.${DOMAINNAME}`)
    - traefik.http.services.picoshare.loadbalancer.server.port=4001
    volumes:
    - ${APPDATA_DIR}/picoshare:/data
