services:
  polaris:
    container_name: polaris
    image: registry.gitlab.com/connectical/container/polaris
    restart: unless-stopped
    hostname: polaris
    networks:
    - traefik_network
    labels:
    - homepage.description=Music Browsing and Streaming
    - homepage.group=Media
    - homepage.href=https://polaris.${DOMAINNAME}/
    - homepage.icon=mdi-music
    - homepage.name=Polaris
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=polaris
    - traefik.enable=true
    - traefik.http.routers.polaris.rule=Host(`polaris.${DOMAINNAME}`)
    - traefik.http.services.polaris.loadbalancer.server.port=5050
    volumes:
    - ${MEDIA_DIR}/music:/music:rw
    - ${APPDATA_DIR}/polaris/cache:/var/cache/polaris:rw
    - ${APPDATA_DIR}/polaris/data:/var/lib/polaris:rw
