services:
  graphhopper:
    image: israelhikingmap/graphhopper
    command: --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host
      0.0.0.0
    restart: unless-stopped
    container_name: graphhopper
    hostname: graphhopper
    networks:
    - traefik_network
    labels:
    - homepage.description=OpenStreetMap Routing Server
    - homepage.group=Maps and GPS
    - homepage.href=https://graphhopper.${DOMAINNAME}/
    - homepage.icon=mdi-map-legend
    - homepage.name=Graphhopper
    - lostack.duration=15m
    - lostack.primary=true
    - lostack.tags=routing,gps,osm,server
    - lostack.project_url=https://github.com/graphhopper/graphhopper
    - lostack.details=GraphHopper is a fast and memory-efficient routing engine released under Apache License 2.0. It can be used as a Java library or standalone web server to calculate the distance, time, turn-by-turn instructions and many road attributes for a route between two or more points. Beyond this "A-to-B" routing it supports "snap to road", Isochrone calculation, mobile navigation and more. GraphHopper uses OpenStreetMap and GTFS data by default and it can import other data sources too.
    - sablier.enable=true
    - sablier.group=graphhopper
    - traefik.enable=true
    - traefik.http.routers.graphhopper.rule=Host(`graphhopper.${DOMAINNAME}`)
    - traefik.http.services.graphhopper.loadbalancer.server.port=8989
