services:
  graphhopper:
    image: israelhikingmap/graphhopper
    command: --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host
      0.0.0.0
    restart: unless-stopped
    container_name: graphhopper
    hostname: graphhopper
    networks:
    - traefik_network
    labels:
    - homepage.description=OpenStreetMap Routing Server
    - homepage.group=Maps and GPS
    - homepage.href=https://graphhopper.${DOMAINNAME}/
    - homepage.icon=mdi-map-legend
    - homepage.name=Graphhopper
    - sablier-station.duration=15m
    - sablier-station.primary=true
    - sablier.enable=true
    - sablier.group=graphhopper
    - traefik.enable=true
    - traefik.http.routers.graphhopper.rule=Host(`graphhopper.${DOMAINNAME}`)
    - traefik.http.services.graphhopper.loadbalancer.server.port=8989
