services:
  sftpgo:
    container_name: sftpgo
    image: drakkan/sftpgo:edge
    restart: unless-stopped
    hostname: sftpgo
    networks:
    - traefik_network
    labels:
    - homepage.description=Flexible SFTP Server
    - homepage.group=FTP
    - homepage.href=https://sftpgo.${DOMAINNAME}/
    - homepage.icon=sftpgo
    - homepage.name=Sftpgo
    - lostack.duration=15m
    - lostack.primary=true
    - lostack.tags=sftp,http,https,ftp,ftps,webdav,s3
    - lostack.project_url=https://github.com/drakkan/sftpgo
    - lostack.details=Full-featured and highly configurable SFTP, HTTP/S, FTP/S and WebDAV server - S3, Google Cloud Storage, Azure Blob
    - sablier.enable=true
    - sablier.group=sftpgo
    - traefik.enable=true
    - traefik.http.routers.sftpgo.rule=Host(`sftpgo.${DOMAINNAME}`)
    - traefik.http.services.sftpgo.loadbalancer.server.port=8080
