services:
  pictshare:
    container_name: pictshare
    image: hascheksolutions/pictshare:2
    hostname: pictshare
    networks:
    - traefik_network
    labels:
    - 'homepage.description=Image Hosting '
    - homepage.group=Media
    - homepage.href=https://pictshare.${DOMAINNAME}/
    - homepage.icon=mdi-image
    - homepage.name=Pictshare
    - sablier-station.duration=15m
    - sablier-station.primary=true
    - sablier.enable=true
    - sablier.group=pictshare
    - traefik.enable=true
    - traefik.http.routers.pictshare.rule=Host(`pictshare.${DOMAINNAME}`)
    - traefik.http.services.pictshare.loadbalancer.server.port=80
    volumes:
    - ${MEDIA_DIR}/images:/var/www/data
