services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    restart: always
    hostname: viseron
    networks:
    - traefik_network
    labels:
    - homepage.description=NVR with AI
    - homepage.group=Video Surveilance
    - homepage.href=https://viseron.${DOMAINNAME}/
    - homepage.icon=viseron
    - homepage.name=Viseron
    - sablier-station.duration=15m
    - sablier-station.primary=true
    - sablier.enable=true
    - sablier.group=viseron
    - traefik.enable=true
    - traefik.http.routers.viseron.rule=Host(`viseron.${DOMAINNAME}`)
    - traefik.http.services.viseron.loadbalancer.server.port=8888
    volumes:
    - ${MEDIA_DIR}/recordings:/recordings
    - ${APPDATA_DIR}/viseron:/config
    - /etc/localtime:/etc/localtime:ro
