services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest
    container_name: xbackbone
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
    restart: unless-stopped
    hostname: xbackbone
    networks:
    - traefik_network
    labels:
    - homepage.description=Sharing + Integrations
    - homepage.group=File Transfer
    - homepage.href=https://xbackbone.${DOMAINNAME}/
    - homepage.icon=xbackbone
    - homepage.name=Xbackbone
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=xbackbone
    - traefik.enable=true
    - traefik.http.routers.xbackbone.rule=Host(`xbackbone.${DOMAINNAME}`)
    - traefik.http.services.xbackbone.loadbalancer.server.port=80
    volumes:
    - ${APPDATA_DIR}/xbackbone:/config
