services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    networks:
    - traefik_network
    restart: unless-stopped
    environment:
      -ND_SCANSCHEDULE: 1h
      -ND_LOGLEVEL: info
      -ND_SESSIONTIMEOUT: 24h
      -ND_BASEURL: ''
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    volumes:
    - ${APPDATA_DIR}/navidrome:/data
    - ${MEDIA_DIR}/music:/music:ro
    labels:
    - traefik.enable=true
    - traefik.http.routers.navidrome.rule=Host(`navidrome.${DOMAINNAME}`)
    - traefik.http.services.navidrome.loadbalancer.server.port=4533
    - homepage.name=Navidrome
    - homepage.group=Media
    - homepage.icon=navidrome
    - homepage.description=Music Player
    - homepage.href=https://navidrome.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=navidrome
    - lostack.duration=1h
    - lostack.primary=true
