services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    user: root
    networks:
    - traefik_network
    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAINNAME}
    volumes:
    - ${CONFIG_DIR}/homepage:/app/config
    - ${LOGS_DIR}/homepage:/app/config/logs
    - ${CONFIG_DIR}/homepage/images:/app/public/images
    - ${DOCKER_SOCKET}:/var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.http.routers.homepage.rule=Host(`${DOMAINNAME}`)
    - traefik.http.services.homepage.loadbalancer.server.port=3000
    - homepage.name=Homepage
    - homepage.group=Services
    - homepage.icon=homepage
    - homepage.description=Environment Dashboard
    - homepage.href=https://${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=homepage
    - sablier-station.duration=45m
    - sablier-station.primary=true
