services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    privileged: true
    devices:
    - /dev/kmsg
    restart: unless-stopped
    hostname: cadvisor
    networks:
    - traefik_network
    labels:
    - homepage.description=Container Resource Analysis
    - homepage.group=Container Management
    - homepage.href=https://cadvisor.${DOMAINNAME}/
    - homepage.icon=cadvisor
    - homepage.name=Cadvisor
    - sablier-station.duration=15m
    - sablier-station.primary=true
    - sablier.enable=true
    - sablier.group=cadvisor
    - traefik.enable=true
    - traefik.http.routers.cadvisor.rule=Host(`cadvisor.${DOMAINNAME}`)
    - traefik.http.services.cadvisor.loadbalancer.server.port=8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
