services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    hostname: linkding
    networks:
    - traefik_network
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.http.routers.linkding.rule=Host(`linkding.${DOMAINNAME}`)
    - traefik.http.services.linkding.loadbalancer.server.port=9090
    - homepage.name=Linkding
    - homepage.group=Apps
    - homepage.icon=linkding
    - homepage.description=Bookmark Manager
    - homepage.href=https://linkding.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=linkding
    - sablier-station.duration=15m
    - sablier-station.primary=true
    volumes:
    - ${APPDATA_DIR}/linkding:/etc/linkding/data
    env_file:
    - .env
